### ISSUE TITLE
player bullet is too slow

### ISSUE THREAD

**Issue by JB1zzel** [SimonGreenaway/QL-Space-Invaders#35]
Player bullet is much slower than arcade version.

Also, invader bullet is probably a little too slow too. See example:

[https://youtu.be/MU4psw3ccUI](url)

**Comment by SimonGreenaway** [comment]
Yep! I need to do some mame comparisons....

**Comment by SimonGreenaway** [comment]
Now made twice as fast. Added extra hit detection to cover increased delta.
