### ISSUE TITLE
moon background

### ISSUE THREAD

**Issue by JB1zzel** [SimonGreenaway/QL-Space-Invaders#36]
Would it be possible to add a moon background?

See example in 4 colour mode:

![image](https://github.com/SimonGreenaway/QL-Space-Invaders/assets/86372800/aedc6177-6816-4a2e-a874-d74dae9273ac)

**Comment by SimonGreenaway** [comment]
I like! What is the source of this image? Or better, can you do the above in mode 8?

**Comment by JB1zzel** [comment]
Very rough mock up

![spacei](https://github.com/SimonGreenaway/QL-Space-Invaders/assets/86372800/846715c9-cd50-4446-a2ee-fd57c8b674a5)

**Comment by SimonGreenaway** [comment]
No panic, I have a HQ image I can convert....

**Comment by JB1zzel** [comment]
![image](https://github.com/SimonGreenaway/QL-Space-Invaders/assets/86372800/3b2d162e-7906-414b-9922-f92a1050c6c7)
 Here! in Mode 8. Can be made darker if needed.

**Comment by JB1zzel** [comment]
I can make it darker if needed

**Comment by SimonGreenaway** [comment]
![image](https://github.com/SimonGreenaway/QL-Space-Invaders/assets/29223933/9b31b666-d9ee-4414-9516-b9907ae2e385)

**Comment by SimonGreenaway** [comment]
It looks great! Maybe a little darker?

**Comment by JB1zzel** [comment]
![image](https://github.com/SimonGreenaway/QL-Space-Invaders/assets/86372800/47e01afc-6ef9-4765-a391-80009c65fb8c)

Darker - and moved the moon up a little for a clearer hud

![image](https://github.com/SimonGreenaway/QL-Space-Invaders/assets/86372800/9831e6d2-d46e-48f7-8480-9fc01273de38)

2 versions

**Comment by SimonGreenaway** [comment]
![image](https://github.com/SimonGreenaway/QL-Space-Invaders/assets/29223933/2c7e7bd6-1d4f-4bd9-82dc-8496fd709da6)

**Comment by SimonGreenaway** [comment]
However, the moon plays havoc with the collison detection for the bullets. So, it basically becomes a large base for the player! I'll have to think how to fix that.

**Comment by JB1zzel** [comment]
Does collision look for green pixels? I could try a no-green image?

**Comment by SimonGreenaway** [comment]
That might work. Only look for green pixels for the invaders bullets and white for the invaders....

**Comment by SimonGreenaway** [comment]
A green mask ANDed with the screen should quickly do the green. White... hmmm....

**Comment by SimonGreenaway** [comment]
And..... damage to bases won't show the moonscape behind. Tricky.

**Comment by SimonGreenaway** [comment]
Got the bullets working...

**Comment by SimonGreenaway** [comment]
![image](https://github.com/SimonGreenaway/QL-Space-Invaders/assets/29223933/b77d1670-9a4a-41c8-be67-f3abefa8c26c)

Oh yeah, green is part of yellow!

**Comment by JB1zzel** [comment]
That looks good, does it work?
