### ISSUE TITLE
Moon_scr corrupts

### ISSUE THREAD

**Issue by Jobd0ne** [SimonGreenaway/QL-Space-Invaders#42]
when testing this release on emulation , with 2 different emulators, the moon_scr (which is missing from the flp image) becomes corrupt when switching from player2 back to player1. fine for player2 though.

**Comment by Jobd0ne** [comment]
![moon](https://github.com/SimonGreenaway/QL-Space-Invaders/assets/159623993/169dca0d-6970-42c7-a204-7bf86b005fda)

**Comment by SimonGreenaway** [comment]
Copy of saved bases was duff, corrected.
